spring:

  datasource:
    password: '1221'
    url: jdbc:mysql://localhost:3306/cumpar_eu_project
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

